### ISSUE TITLE
[PersonnelApiController] Manque de contrôle d'accès dans addPersonnelToDepartement

### ISSUE THREAD

**Issue by LockBlock-dev** [Dannebicque/intranetV3#146]
### Description
L'endpoint `/api/personnel/personnel/departement/add/{slug}/{departement}` ne vérifie pas que l'utilisateur à l'origine de la requête possède les droits nécessaires pour effectuer cette opération :
https://github.com/Dannebicque/intranetV3/blob/2fa82fbc848bbf03199e78bef9d6c12084576abb/src/Controller/api/PersonnelApiController.php#L108-L129

### Étapes pour reproduire
1. Connectez-vous à l'application en utilisant, par exemple, un compte étudiant qui ne possède pas les autorisations requises. Cela mettra en évidence le problème.
2. Essayez d'ajouter un membre du personnel à un département (par exemple, le département par défaut).
3. L'application autorisera l'opération sans effectuer de vérification.

### Comportement attendu
L'application devrait renvoyer une erreur lorsque l'utilisateur à l'origine de la requête ne possède pas les droits nécessaires pour effectuer cette opération (comme `ROLE_ADMINISTRATIF`).

**Comment by Dannebicque** [comment]
Bonjour,
Merci pour cette information et remontée de bug. Le correctif est en ligne (pour Troyes et en cours pour Reims).
