### ISSUE TITLE
[Stages]envoi pour signature

### ISSUE THREAD

**Issue by CyndelHerolt** [Dannebicque/intranetV3#300]
erreur 500 lors de l'envoi à l'étudiant pour signature : "trim(): Passing null to parameter #1 ($string) of type string is deprecated"
j'ai pas encore trouvé le 'trim()' en question

**Comment by Dannebicque** [comment]
J'ai fait le commit. Je pense que c'est le chemin de sauvegarde qui n'etait pas bon. Il y avait deux fois la base du dossier. A confirmer. Ce n'est pas sur la prod

**Comment by CyndelHerolt** [comment]
Ok super je test demain matin
